version: '3.8'

services:

  api:
    build: .
    container_name: api
    environment:
      - POSTGRES_USER=postgres      
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=terraform tf-db.czjiom3rtt6e.us-east-1.rds.amazonaws.com
    ports:
      - "5432:5432"
    volumes:
      - /postgres:/var/lib/postgresql/data


